language: node_js
node_js:
  - 5.5.0
addons:
    code_climate:
        repo_token: 41e795c11701290ada257c43695762660e38add375e731a752e8724792fec7c2
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
